/**
 * Weapon archetypes.
 *
 * Eight authored; three are flagged `prototype` and are what Tier 1 ships with.
 * They are picked to be maximally unlike each other — a slow committed
 * single-shot, a sustained beam with a ramp, and an arcing area denial lob —
 * because the point of the prototype is to prove archetypes feel different
 * before any of them get stat-reskinned into a content list.
 */
import type { WeaponArchetype } from '../types.js';

export const WEAPON_ARCHETYPES: readonly WeaponArchetype[] = [
  {
    id: 'adze',
    name: 'Adze',
    family: 'Slug Rifle',
    damageType: 'percussive',
    behavior: 'hitscan',
    baseDamage: 62,
    pellets: 1,
    fireInterval: 26,
    magazine: 6,
    reloadTicks: 68,
    spread: 0.006,
    projectileSpeed: 0,
    range: 900,
    critChance: 0.18,
    critMult: 2.4,
    recoil: 5.2,
    hitstop: 5,
    handling: 0.9,
    status: { kind: 'stagger', chance: 0.22, magnitude: 1, durationTicks: 14 },
    prototype: true,
    flavor: 'A bolt-fed slug thrower. One round, one decision. Reloads like a ritual.',
  },
  {
    id: 'thurible',
    name: 'Thurible',
    family: 'Solar Lance',
    damageType: 'solar',
    behavior: 'beam',
    baseDamage: 5.4,
    pellets: 1,
    fireInterval: 2,
    magazine: 120,
    reloadTicks: 92,
    spread: 0,
    projectileSpeed: 0,
    range: 460,
    critChance: 0.04,
    critMult: 1.6,
    recoil: 0.5,
    hitstop: 1,
    handling: 0.82,
    status: { kind: 'ignite', chance: 0.06, magnitude: 9, durationTicks: 120 },
    prototype: true,
    flavor: 'Sustained lance. Damage ramps the longer you hold the line on a target.',
  },
  {
    id: 'censer',
    name: 'Censer',
    family: 'Caustic Caster',
    damageType: 'caustic',
    behavior: 'lob',
    baseDamage: 44,
    pellets: 1,
    fireInterval: 34,
    magazine: 4,
    reloadTicks: 76,
    spread: 0.02,
    projectileSpeed: 9.5,
    range: 700,
    critChance: 0.05,
    critMult: 1.8,
    recoil: 3.0,
    hitstop: 3,
    handling: 0.95,
    status: { kind: 'corrosion', chance: 0.85, magnitude: 14, durationTicks: 200 },
    prototype: true,
    flavor: 'Lobs a sealed censer of rot. Area denial. Shields laugh at it; meat does not.',
  },
  {
    id: 'vespers',
    name: 'Vespers',
    family: 'Arc Coil',
    damageType: 'arc',
    behavior: 'projectile',
    baseDamage: 21,
    pellets: 1,
    fireInterval: 7,
    magazine: 32,
    reloadTicks: 60,
    spread: 0.03,
    projectileSpeed: 16,
    range: 520,
    critChance: 0.08,
    critMult: 1.7,
    recoil: 1.4,
    hitstop: 2,
    handling: 1.05,
    status: { kind: 'disrupt', chance: 0.3, magnitude: 1, durationTicks: 80 },
    prototype: false,
    flavor: 'Coil-fed. Strips shielding in seconds and leaves it unable to knit back.',
  },
  {
    id: 'maw',
    name: 'Maw',
    family: 'Scattergun',
    damageType: 'percussive',
    behavior: 'hitscan',
    baseDamage: 15,
    pellets: 9,
    fireInterval: 30,
    magazine: 5,
    reloadTicks: 84,
    spread: 0.16,
    projectileSpeed: 0,
    range: 190,
    critChance: 0.1,
    critMult: 2.0,
    recoil: 7.5,
    hitstop: 7,
    handling: 1.0,
    status: { kind: 'stagger', chance: 0.5, magnitude: 1, durationTicks: 18 },
    prototype: false,
    flavor: 'Short, wide, and final. Nine pellets is a suggestion at range and a verdict up close.',
  },
  {
    id: 'obelisk',
    name: 'Obelisk',
    family: 'Rail',
    damageType: 'arc',
    behavior: 'hitscan',
    baseDamage: 180,
    pellets: 1,
    fireInterval: 62,
    magazine: 3,
    reloadTicks: 110,
    spread: 0,
    projectileSpeed: 0,
    range: 1400,
    critChance: 0.25,
    critMult: 3.0,
    recoil: 11,
    hitstop: 9,
    handling: 0.72,
    prototype: false,
    flavor: 'Charge, hold, exhale. Pierces every body between you and the horizon.',
  },
  {
    id: 'reliquary',
    name: 'Reliquary',
    family: 'Swarm Launcher',
    damageType: 'solar',
    behavior: 'projectile',
    baseDamage: 12,
    pellets: 5,
    fireInterval: 44,
    magazine: 3,
    reloadTicks: 96,
    spread: 0.12,
    projectileSpeed: 7,
    range: 600,
    critChance: 0.02,
    critMult: 1.5,
    recoil: 4.0,
    hitstop: 2,
    handling: 0.88,
    status: { kind: 'ignite', chance: 0.35, magnitude: 7, durationTicks: 100 },
    prototype: false,
    flavor: 'Releases a votive swarm that finds its own way to the heat.',
  },
  {
    id: 'pyre',
    name: 'Pyre',
    family: 'Sear Thrower',
    damageType: 'solar',
    behavior: 'projectile',
    baseDamage: 4.2,
    pellets: 2,
    fireInterval: 3,
    magazine: 150,
    reloadTicks: 88,
    spread: 0.14,
    projectileSpeed: 11,
    range: 165,
    critChance: 0.01,
    critMult: 1.4,
    recoil: 0.8,
    hitstop: 1,
    handling: 0.93,
    status: { kind: 'ignite', chance: 0.18, magnitude: 8, durationTicks: 140 },
    prototype: false,
    flavor: 'Close-range gout. Fills a corridor with standing fire and regret.',
  },
];

const BY_ID = new Map(WEAPON_ARCHETYPES.map((w) => [w.id, w]));

export function getArchetype(id: string): WeaponArchetype {
  const a = BY_ID.get(id);
  if (!a) throw new Error(`unknown weapon archetype: ${id}`);
  return a;
}

export const PROTOTYPE_ARCHETYPES = WEAPON_ARCHETYPES.filter((w) => w.prototype);
